-- Add missing columns to products table
ALTER TABLE products
ADD COLUMN bulk_discount VARCHAR(100) DEFAULT NULL,
ADD COLUMN bulk_price FLOAT DEFAULT NULL,
ADD COLUMN minimum_quantity INT DEFAULT 1,
ADD COLUMN sustainability_score INT NOT NULL DEFAULT 0,
ADD COLUMN materials VARCHAR(200) DEFAULT NULL,
ADD COLUMN certifications VARCHAR(200) DEFAULT NULL,
ADD COLUMN `condition` VARCHAR(20) DEFAULT 'new',
ADD COLUMN is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP; 